### ISSUE TITLE
Smart publishing

### ISSUE THREAD

**Issue by ysimonson** [node-bus/node-bus#10]
Currently, the client sends a message like this when it adds its first listener to an event:

{"type": "listen", "event": "some.event.name"}

And a message like this when it removes the last listener of an event:

{"type": "unlisten", "event": "some.event.name"}

The server should listen for these message types and ensure that it only sends events to the clients that are listening.

**Comment by jasonwyatt** [comment]
as far as i know, the client doesn't send those events.. but it could/should.

**Comment by ysimonson** [comment]
Apparently the listen message type has been removed. But unlisten is still sent:
http://github.com/node-bus/node-bus/blob/master/src/bus.client.js#L246

**Comment by node-bus** [comment]
Feature added back in.
