### ISSUE TITLE
Modularize the code base

### ISSUE THREAD

**Issue by ysimonson** [node-bus/node-bus#11]
I think the following changes would really help clean up the code:

1) A means of having shared code between the client and server. With the next few iterations, there will be a lot of shared logic. We could always create a build process to simplify deployment.

2) Make the comet method used by the client pluggable, similar to how it's done on the server-end. Again this might be something we could condense into a single code base.

3) Maybe spin the comet engine into a separate project. Especially because this might be useful for other projects.

**Comment by ysimonson** [comment]
I'm going to prioritize this because the proposed new features would be affected by this, so it should be finished first.

**Comment by node-bus** [comment]
Communication layer has been moved out to node-comet. Closing.
