### ISSUE TITLE
Make it easy to publish and subscribe to events on the server side.

### ISSUE THREAD

**Issue by jasonwyatt** [node-bus/node-bus#7]
Was kind of an oversight in the original implementation of node-bus.  It should be easy (similar to the client-side simplicity) to publish-to and subscribe-to events on the server side.   

This could be accomplished by simply adding   subscribe/sub, unsubscribe/unsub and publish/pub functions to the "exports" object in bus.server.js.   Might have to do a little design thinking on it, however.

**Comment by ysimonson** [comment]
It would be nice if this could share the same codebase as that of the client.

**Comment by ysimonson** [comment]
Moving to 0.4

**Comment by ysimonson** [comment]
Added in 0.4
